name: Holzi
favicon: null
layout_spectrum: 0.49772990262135863
typography_spectrum: 0.55013
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#5e543b'
    - '#fdf0dd'
    - '#c9b091'
    - '#a9371a'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
