typography_spectrum: 0.433081149822101
color:
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
  brandStrength: 0.5474486381281167
  lightness: 0.45469522452913225
  saturation: 0.056197009049355984
  rhythmicContrast: 0.10209069261327386
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7490522698499262
analytics:
  google: null
  facebook: null
  twitter: null
name: Holzi
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Test
    url: 'http://www.borntobebackstage.com/'
    type: external
favicon: null
title: Yeah!
description: Awesome
purpose: []
