name: Holzi
favicon: null
layout_spectrum: 0.49772990262135863
typography_spectrum: 0.17912672040984035
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.2519854982383549
  lightness: 0.5470433752052486
  saturation: 0.18419770104810596
  rhythmicContrast: 0.8352638366632164
purpose: []
