typography_spectrum: 0.55013
color:
  brandColors:
    - '#020918'
    - '#d6d6d8'
    - '#243247'
    - '#9494a2'
    - '#575f73'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.51113
analytics:
  google: null
  facebook: null
  twitter: null
name: Holzi
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Yeah!
description: Awesome
purpose: []
